#!/bin/bash (source)

if [[ -d $HOME/.cargo/bin ]]; then
    export PATH="$HOME/.cargo/bin:$PATH"
    source $(rustc --print sysroot)/etc/bash_completion.d/cargo
fi

if [[ -d $HOME/.pyenv ]]; then
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"

    if command -v pyenv &> /dev/null; then
        eval "$(pyenv init - bash)"
        eval "$(pyenv virtualenv-init - bash)"
        source $(pyenv root)/completions/pyenv.bash
    fi
fi

if [[ -e $HOME/.poetry/env ]]; then
    source $HOME/.poetry/env
fi

if [[ -e $HOME/.nodenv/bin/nodenv ]]; then
    export PATH="$HOME/.nodenv/bin:$PATH"
    eval "$(nodenv init - bash)"
fi

if command -v nvim &> /dev/null; then
    export EDITOR=nvim
fi

if command -v bat &> /dev/null; then
    export BAT_THEME=OneHalfDark
    alias cat="$(command -v bat) --theme $BAT_THEME"
fi
command -v exa &> /dev/null && alias ls="$(command -v exa)"

if command -v starship &> /dev/null; then
    eval "$(starship init zsh)"
fi
