#!/bin/bash (source)

if [[ -d $HOME/.local/bin ]]; then
    export PATH=$HOME/.local/bin:$PATH
fi

if [[ -r $HOME/.cargo/env ]]; then
    source "$HOME/.cargo/env"
    source $(rustc --print sysroot)/etc/bash_completion.d/cargo
    if command -v sccache &> /dev/null; then
        export RUSTC_WRAPPER="$(command -v sccache)"
    fi
fi

if [[ -d $HOME/.pyenv ]]; then
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"

    if command -v pyenv &> /dev/null; then
        eval "$(pyenv init - bash)"
        eval "$(pyenv virtualenv-init - bash)"
        source $(pyenv root)/completions/pyenv.bash
    fi
fi

if [[ -e $HOME/.poetry/env ]]; then
    source $HOME/.poetry/env
    eval "$(poetry completions bash)"
fi

if [[ -e $HOME/.nodenv/bin/nodenv ]]; then
    export PATH="$HOME/.nodenv/bin:$PATH"
    eval "$(nodenv init - bash)"
fi

if command -v nvim &> /dev/null; then
    export EDITOR=nvim
fi

if command -v bat &> /dev/null; then
    export BAT_THEME=Dracula
    alias cat="$(command -v bat) --theme $BAT_THEME"
fi
command -v exa &> /dev/null && alias ls="$(command -v exa)"

if command -v starship &> /dev/null; then
    eval "$(starship init bash)"
fi

if [[ -f $HOME/.fzf.bash ]]; then
    source $HOME/.fzf.bash
    export FZF_DEFAULT_OPTS="--no-mouse"
    if command -v fd &> /dev/null; then
        export FZF_DEFAULT_COMMAND="fd --type f"
        export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
    fi
fi
