unbind '"'
unbind %

bind - split-window -v
bind r source-file ~/.tmux.conf
bind | split-window -h

set -g base-index 1
set -g default-terminal "screen-256color"
# set -g mouse on

set -gw mode-keys vi
set -gw status-keys vi

set -s escape-time 0

set-option -g allow-rename off
set-option -g renumber-windows on

if '[ -f ~/.tmux.conf.local ]' 'source ~/.tmux.conf.local'

set -g status-style fg=black,bg=green

set -g status-left "#[bg=white] \u274f #S "
set -g status-right "#[bg=white] \uf5ef %d-%m-%Y %H:%M "

set -g window-status-format " #I #W "
set -g window-status-current-format "#[bg=cyan] #I #W "
set -g window-status-separator ""
